"""
Guidance result schema.
"""

from __future__ import annotations

from pydantic import BaseModel, Field, model_validator

from app.schemas.common import GuidanceSource


class GuidanceResult(BaseModel):
    """
    Personalised health guidance generated by Mistral AI or the rule-based
    fallback, grounded in the triage result and reported symptoms.
    """

    source: GuidanceSource = Field(
        default="fallback",
        description="Which guidance strategy produced this result.",
    )
    model_used: str | None = Field(
        default=None,
        description="LLM model identifier, if guidance was LLM-generated.",
    )
    provider_used: str | None = Field(
        default=None,
        description="Inference provider, if applicable.",
    )
    explanation: str = Field(
        description="Plain-language interpretation of the screening result."
    )
    urgency_guidance: str = Field(
        description="Recommended follow-up urgency and action."
    )
    food_advice: str = Field(
        description="Dietary suggestions relevant to the result."
    )
    next_steps: list[str] = Field(
        description="Ordered list of concrete next actions for the user.",
        min_length=1,
    )

    @model_validator(mode="after")
    def _llm_fields_present_when_mistral(self) -> "GuidanceResult":
        if self.source == "mistral" and (
            self.model_used is None or self.provider_used is None
        ):
            raise ValueError(
                "model_used and provider_used must be set when source='mistral'."
            )
        return self
