import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

// Assuming identical type structure to the one in useScreening hook
import { AnalyzeResponse } from '../types';

/**
 * Generates a professional clinical PDF report using jsPDF
 */
export async function generatePdfReport(analysis: AnalyzeResponse) {
  const doc = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4',
  });

  const pageWidth = doc.internal.pageSize.getWidth();
  let yPos = 20;

  // Colors
  const accent = [200, 0, 30] as [number, number, number]; // Red accent
  const darkText = [30, 30, 30] as [number, number, number];
  const lightText = [100, 100, 100] as [number, number, number];

  // Title / Header
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(22);
  doc.setTextColor(...accent);
  doc.text('AnemiaLens Clinical Report', 15, yPos);
  
  yPos += 8;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...lightText);
  doc.text(`Generated: ${new Date().toLocaleString()}`, 15, yPos);
  doc.text('Non-diagnostic Screening Aid Only', pageWidth - 15, yPos, { align: 'right' });
  yPos += 12;

  // Divider
  doc.setDrawColor(220, 220, 220);
  doc.line(15, yPos, pageWidth - 15, yPos);
  yPos += 15;

  // Executive Summary Section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...darkText);
  doc.text('1. Executive Triage Summary', 15, yPos);
  yPos += 10;

  // Convert triage string to readable
  const triageLabel = analysis.triage.band.replace(/_/g, ' ').toUpperCase();
  
  autoTable(doc, {
    startY: yPos,
    head: [['Metric', 'Value', 'Details']],
    body: [
      ['Triage Band', triageLabel, `Score: ${analysis.triage.score}`],
      ['Screening Result', analysis.prediction?.screening_label.replace(/_/g, ' ') || 'N/A', `Risk: ${((analysis.prediction?.anemia_risk || 0) * 100).toFixed(1)}%`],
      ['Estimated Hemoglobin', `${analysis.prediction?.predicted_hemoglobin?.toFixed(1) || 'N/A'} g/dL`, `Confidence: ${((analysis.prediction?.confidence || 0) * 100).toFixed(0)}%`],
    ],
    theme: 'grid',
    headStyles: { fillColor: accent, textColor: 255 },
    styles: { font: 'helvetica', fontSize: 10 },
  });
  
  yPos = (doc as any).lastAutoTable.finalY + 15;

  // Clinical Brief section
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...darkText);
  doc.text('2. Clinical Brief', 15, yPos);
  yPos += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.setTextColor(...darkText);
  
  const briefText = analysis.clinical_brief.share_text || analysis.clinical_brief.headline;
  const briefLines = doc.splitTextToSize(briefText.replace(/\\n/g, '\n'), pageWidth - 30);
  doc.text(briefLines, 15, yPos);
  yPos += briefLines.length * 5 + 10;

  // Check for page break
  if (yPos > 250) {
    doc.addPage();
    yPos = 20;
  }

  // Symptom Data
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...darkText);
  doc.text('3. Reported Symptoms', 15, yPos);
  yPos += 8;

  const presentSymptoms = Object.entries(analysis.symptoms)
    .filter(([_, value]) => value === true)
    .map(([key, _]) => key.replace(/_/g, ' '));

  const symptomList = presentSymptoms.length > 0 
    ? presentSymptoms.join(', ')
    : 'None reported';
    
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`Present: ${symptomList}`, 15, yPos);
  yPos += 15;

  // Footer / Disclaimer
  const pageHeight = doc.internal.pageSize.getHeight();
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const disclaimer = "DISCLAIMER: This report is generated by an AI screening tool and is NOT a medical diagnosis. The estimated hemoglobin and anemia risk values are predictive aids intended to facilitate clinical triage and decision-making. A formal laboratory blood test (CBC) is required for definitive diagnosis.";
  const disclaimerLines = doc.splitTextToSize(disclaimer, pageWidth - 30);
  doc.text(disclaimerLines, 15, pageHeight - 20);

  // Save the PDF
  doc.save(`anemialens-report-${Date.now()}.pdf`);
}
